### ISSUE TITLE
Improve chemistry library modularity and clean up code.

### ISSUE THREAD

**Issue by guanghaolow** [microsoft/QuantumLibraries#54]
Goal: Address the following comment. "What totally make sense is to use Broombridge for input and output of a whole sample / algorithm. But my feeling (and limited understanding) so far is that the workflow makes things complicated because functionalities I've seen in the libraries seem to "entangle" or "tie" a number of objects and concepts that actually exist separately and for which a lot of modifications and research is done."

Addressed partially in this PR #58 

To these ends, we want to separate the basic objects from current large classes to improve code reuse of smaller modules, and improve readability.  Examples
- FermionTerm currently has way too many overlapping constructors, comparers, and methods. This must be simplified. 
- FermionTerm should be inherit a simpler class for sequences of operators, and build off that. 
- FermionTerm should also have terms indexed by just integers. The current approach of indexing with SpinOrbitals is too unwieldy. 
- The index conversion of SpinOrbitals to integers should be invoked early and only once when the problem is defined. 
- FermionHamiltonian has too many metadata variables. This class should just be about the Hamiltonian, and we should create another class e.g. `ProblemInstance` than has a FermionHamiltonian member, and problem metadata. Right now, these are all packaged into one hard-to-understand class.
- Initial state Ansatzes should be split off from FermionHamiltonian

### TODO ###
- [x] Create generic Hamiltonian class for general creation, manipulation, and analysis of Hamiltonians.
  - [x] Create orbital integral Hamiltonian class
  - [x] Create fermion Hamiltonian class
  - [x] Create Pauli Hamiltonian class. 
   - [x] Decide ~between multiple subclasses for different encoding schemes, e,g, generic Pauli Hamiltonian class, or~ single point-of-reference class.

- [x] Create generic initial state ansatz class
  - [x] Create Hartree-Fock state class
  - [x] Create Multi-Configurational state class
  - [x] Create Unitary Coupled-Cluster class

- [x] Create abstract ladder (raising / lowering) operator class
  - [x] Create fermion term classes (These are strongly typed depending on property to reduce constructor parameters and eliminate ambiguity in coefficient and ordering conventions).
    - [x] FermionTerm class for normal ordered-and index-ordered fermion terms (used in state prepataion).
    - [x] HermitianFermionTerm class for a Hermitian combination of fermion term, which has a different ordering version (used in Hamiltonian class)

- [ ] Create accessible problem description container and configuration file for non-specialist users.
- [ ] Create convenience functions and configuration files for common workflows.

Split Broombridge into multiple parts
  - [x] Version control
  - [x] Data structures
  - [x] Serialization / Deserialization

Create explicit interface for converting between
  - [x] Orbital integrals and fermions for both terms and Hamiltonians.
  - [x] fermions and Paulis for both terms and Hamiltonians and states. 
  - [x] Broombridge and the relevant classes above.

**Comment by cgranade** [comment]
Resolving this issue based on the contents of the 0.6 release. If we want to make further improvements in 0.9 and later, let's make separate issues for those.
